# Generated by Django 2.2 on 2019-04-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='件名')),
                ('content', models.TextField(max_length=500, verbose_name='件名')),
                ('postdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
